Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-10, with the labels that each got.

#2128 Add CustomMessageRepository, remove BaseActivity
  app/src/main/java/org/jellyfin/androidtv/constant/CustomMessage.kt
  app/src/main/java/org/jellyfin/androidtv/data/repository/CustomMessageRepository.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/UserViewActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/BaseActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/shared/MessageListener.kt
  app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Labels: refactor

#2131 Fix audio player screensaver starting too soon
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#2145 Remove GsonJsonSerializer
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Labels: refactor

#2149 Add PictureViewerFragment as destination
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Labels: bug, enhancement, photos

#2151 Rewrite presenters in Kotlin
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/ChannelCardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/ChannelCardPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomListRowPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomListRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomRowHeaderPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/InfoCardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/InfoCardPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/PositionableListRowPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/PositionableListRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/TextItemPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/TextItemPresenter.kt
Labels: refactor

#2150 Rewrite MyDetailsOverviewRow in Kotlin
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt
Labels: refactor

#2148 Add LifecycleAwareResponse
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRunnable.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/EmptyLifecycleAwareResponse.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/LifecycleAwareResponse.kt
Labels: enhancement, crash

#2155 Check lifecycle state when runnable executes
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
Labels: crash

#2157 Check Lifecycle.State.STARTED instead of Lifecycle.State.INITIALIZED
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/EmptyLifecycleAwareResponse.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/LifecycleAwareResponse.kt
Labels: crash

#2156 Fix PictureViewerFragment crashing when opening photo from latest row
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Labels: crash

#2158 Replace Response<> usages with LifecycleAwareResponse<> in fragments
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: refactor

#2159 Don't use activity.isFinishing()
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#2169 Show picture viewer controls by default
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/res/layout/fragment_picture_viewer.xml
Labels: enhancement, photos

#2170 Automatically hide picture viewer actions after 4 seconds
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Labels: enhancement, photos

#2171 Remove PhotoPlayerActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/res/layout/activity_photo_player.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, photos

#2178 Show keyboard on right on text search fragment
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_search_text.xml
Labels: enhancement

#2193 Add Jetpack Compose support
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#2208 Remove direct GSON dependency
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#2211 Don't use LibraryDreamService.TRANSITION_DURATION in FadeViewSwitcherLayout
  app/src/main/java/org/jellyfin/androidtv/ui/FadeViewSwitcherLayout.kt
Labels: enhancement

#2213 Fix setExoPlayerTrack exception when allStreams is empty
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug, backportable, crash

#2217 Fix EnhancedBrowseFragment registering multiple listeners
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeClickedListener.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeSelectedListener.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
Labels: bug

#2216 Use fade animation when navigating
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: enhancement

#2220 fix seekbar not updating when using ff/rw buttons
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, playback

#2224 Load fresh item data in AudioTrackQueue
  playback/jellyfin/src/main/kotlin/queue/AudioTrackQueue.kt
Labels: bug, playback

#2229 Add placeholder drawable for ImageProvider
  app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
  app/src/main/res/drawable/placeholder_icon.xml
Labels: enhancement

#2228 Fix StartupActivity set destination is ignored
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Labels: bug
