Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-07, with the labels that each got.

#1772 Add external trailer support
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/TrailerUtils.kt
Labels: release-highlight

#1862 Fix live tv guide options not persisting
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/GuideOptionsScreen.kt
Labels: bug

#1868 Fix null text in info row
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: bug

#1863 Remove stateListAnimator from button styles
  app/src/main/res/values/styles.xml
Labels: bug

#1866 Fix inconsistent red color for recordings
  app/src/main/res/drawable/ic_record_series_red.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#1860 Update button order on item details screen
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/res/menu/menu_details_more.xml
Labels: enhancement

#1865 Add support for the Fire Stick 4k Max
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java
  app/src/test/kotlin/util/DeviceUtilsTests.kt
Labels: enhancement

#1864 Fix live tv guide option button styles
  app/src/main/res/layout/live_tv_guide.xml
Labels: enhancement

#1871 Fix sign-in screen claiming invalid credentials when server is unavailable
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
Labels: bug, blocked

#1867 Fix live tv guide load more button height
  app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
  app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug

#1876 fix series logo scaling in player
  app/src/main/res/layout/vlc_player_interface.xml
Labels: bug

#1870 Fix channel logo display
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/res/drawable/tile_tv.xml
Labels: bug

#1861 Fix live tv guide sorting
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
Labels: bug

#1878 handle exoplayer track selection indexes starting at 1
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug

#1875 Update more channels button
  app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/res/drawable/gray_gradient.xml
  app/src/main/res/layout/live_tv_guide.xml
  app/src/main/res/layout/overlay_tv_guide.xml
  app/src/main/res/layout/program_grid_cell.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#1892 Fix channel load more button size in popup guide
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug

#1893 Remove live tv guide banner images
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/res/drawable/banner_kids.jpg
  app/src/main/res/drawable/banner_movie.jpg
  app/src/main/res/drawable/banner_news.jpg
  app/src/main/res/drawable/banner_sports.jpg
  app/src/main/res/drawable/banner_tv.jpg
  app/src/main/res/layout/live_tv_guide.xml
Labels: enhancement, accessibility

#1894 Remove whitespace prepended to the no gude data titles
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: enhancement
