Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-09, with the labels that each got.

#2022 Add empty playback modules for rewrite
  app/build.gradle.kts
  playback/core/build.gradle.kts
  playback/core/src/main/AndroidManifest.xml
  playback/exoplayer/build.gradle.kts
  playback/exoplayer/src/main/AndroidManifest.xml
  playback/jellyfin/build.gradle.kts
  playback/jellyfin/src/main/AndroidManifest.xml
  playback/ui/build.gradle.kts
  playback/ui/src/main/AndroidManifest.xml
  settings.gradle.kts
Labels: refactor

#2028 Add monochrome layer to adaptive icon
  app/src/main/res/drawable-v26/app_icon.xml
Labels: enhancement

#2027 Set defaultFocusHighlightEnabled to false in DefaultCardView
  app/src/main/java/org/jellyfin/androidtv/ui/card/DefaultCardView.kt
Labels: bug

#2029 Fix app crashing when opening "other options" menu in FullDetailsActivity
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
Labels: crash

#2030 Set defaultFocusHighlightEnabled to false in TextUnderButton
  app/src/main/java/org/jellyfin/androidtv/ui/TextUnderButton.kt
Labels: bug

#2032 Replace BaseItemType usages with BaseItemKind (SDK)
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: sdk-migration, refactor

#2033 Always set base item type on custom base item dto instances
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: crash

#2034 Fix missing imports causing a build issue
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: crash

#2035 Add SocketInstance to dependency injection
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Labels: refactor

#2047 Bump Android compile & target version to 33 (Android 13)
  app/build.gradle.kts
  playback/core/build.gradle.kts
  playback/exoplayer/build.gradle.kts
  playback/jellyfin/build.gradle.kts
  playback/ui/build.gradle.kts
  preference/build.gradle.kts
Labels: dependencies, gradle

#1924 Add Quality Selection to Playback Overlay
  app/src/main/java/org/jellyfin/androidtv/constant/QualityProfiles.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoQualityController.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/drawable/ic_select_quality.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, release-highlight

#2071 Fix two crashes when trying to view a person
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: bug, crash

#2073 Use appcompat theme as base
  app/src/main/res/values/theme_jellyfin.xml
Labels: refactor

#2074 Merge StdRowsFragment into HomeFragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
Labels: refactor

#2075 Use MutableObjectAdapter<Row> for rows
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/NotificationsHomeFragmentRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRunnable.java
Labels: refactor

#2076 Use MutableObjectAdapter<Object> as base for ItemRowAdapter
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt
Labels: refactor

#2079 Fix crash when selecting or clicking items in grid view
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeClickedListener.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeSelectedListener.kt
Labels: bug, crash

#2090 Disable jetifier
  gradle.properties
Labels: refactor

#2091 Move package declaration to Gradle build files
  app/src/main/AndroidManifest.xml
  playback/core/build.gradle.kts
  playback/core/src/main/AndroidManifest.xml
  playback/exoplayer/build.gradle.kts
  playback/exoplayer/src/main/AndroidManifest.xml
  playback/jellyfin/build.gradle.kts
  playback/jellyfin/src/main/AndroidManifest.xml
  playback/ui/build.gradle.kts
  playback/ui/src/main/AndroidManifest.xml
  preference/build.gradle.kts
  preference/src/main/AndroidManifest.xml
Labels: refactor

#2092 Fix NPE when live tv program is null
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: bug

#2097 Use AsyncImageView for Live TV program image
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/res/layout/live_tv_guide.xml
Labels: refactor

#2094 Update GitHub actions workflows
  .github/workflows/app-build.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
  .github/workflows/gradlew-update.yaml
  .github/workflows/gradlew-validate.yaml
  .github/workflows/repo-merge-conflict.yaml
  .github/workflows/repo-stale.yaml
Labels: enhancement, ci

#2103 Fix blurhash not showing in CardPresenter
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
Labels: bug

#2102 Don't use KoinJavaComponent in Kotlin files
  app/src/main/java/org/jellyfin/androidtv/data/querying/StdItemQuery.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarView.kt
  app/src/main/java/org/jellyfin/androidtv/util/Utils.kt
Labels: refactor

#2105 Fix series queueing not working
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: bug

#2104 Remove most deprecation annotations
  app/src/main/java/org/jellyfin/androidtv/data/compat/AudioOptions.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/PlaybackException.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamBuilder.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/SubtitleStreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/VideoOptions.java
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.java
Labels: refactor

#2107 Merge StdBrowseFragment and BrowseFolderFragment and rewrite in Kotlin
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
Labels: sdk-migration, refactor

#2108 Always use repeatOnLifecycle instead of launchWhenX functions
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeToolbarFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
Labels: refactor

#2112 Refactor AudioNowPlayingActivity to fragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: refactor

#2113 Refactor FullDetailsActivity to fragment
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: refactor

#2114 Refactor ItemListActivity to fragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: refactor

#2116 Refactor LiveTvGuideActivity to fragment
  app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
  app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: refactor

#2127 Replace Kapt with KSP
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#2124 Use fragment arguments instead of activity intent
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericGridActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GroupedItemsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/UserViewActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchActivity.kt
Labels: refactor
