Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-08, with the labels that each got.

#1951 fix NextUp not working without clearing old video queue items
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: refactor

#1957 Bump Android compile and target SDK to 32 (Android 12L)
  app/build.gradle.kts
  playback/build.gradle.kts
  preference/build.gradle.kts
Labels: dependencies

#1829 Add new experimental picture viewer
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyHandler.kt
  app/src/main/res/drawable/button_bar_back.xml
  app/src/main/res/drawable/button_icon_tint_animated.xml
  app/src/main/res/drawable/ica_play_pause.xml
  app/src/main/res/layout/fragment_picture_viewer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1964 Catch decoding exception in AuthenticationStore
  app/src/main/java/org/jellyfin/androidtv/auth/store/AuthenticationStore.kt
Labels: bug, crash

#1968 Fix alignment of ClockUserView in live TV guide
  app/src/main/res/layout/live_tv_guide.xml
Labels: bug

#1958 Allow app installation on external storage
  app/src/main/AndroidManifest.xml
Labels: enhancement

#1959 Migrate DefaultLifecycleObserver setup to androidx.startup
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/androidtv/ProcessLifecycleInitializer.kt
Labels: refactor

#1965 Fix themes on Android 9 and lower
  app/src/main/java/org/jellyfin/androidtv/ui/shared/AppThemeCallbacks.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
Labels: bug

#1971 Don't open library settings for unsupported types
  app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
Labels: bug

#1972 Properly handle specials in item naming
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#1967 Use AsyncImageView in GuideChannelHeader
  app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
  app/src/main/res/layout/channel_header.xml
Labels: refactor

#1973 Use view binding directly in BrowseGridFragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Labels: refactor

#1978 Migrate InfoLayoutHelper to use SDK models
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/ModelExtensions.kt
Labels: sdk-migration, refactor

#1984 Always use SDK BaseItemPerson and PersonType
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
Labels: sdk-migration, refactor

#1985 Remove unused ApiEventListener from legacy apiclient
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Labels: refactor

#1941 Support previous button in video playlist
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
Labels: enhancement

#1842 Add RTL Support
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/res/layout/activity_audio_now_playing.xml
  app/src/main/res/layout/activity_photo_player.xml
  app/src/main/res/layout/channel_header.xml
  app/src/main/res/layout/enhanced_detail_browse.xml
  app/src/main/res/layout/horizontal_grid_browse.xml
  app/src/main/res/layout/horizontal_scroll_pane.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/layout/live_tv_guide.xml
  app/src/main/res/layout/new_program_record_popup.xml
  app/src/main/res/layout/overlay_tv_guide.xml
  app/src/main/res/layout/program_detail_popup.xml
  app/src/main/res/layout/program_grid_cell.xml
  app/src/main/res/layout/text_under_button.xml
  app/src/main/res/layout/view_card_legacy_image.xml
Labels: enhancement

#1992 fix CommunityRating display
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: bug

#1993 Simplify reportPlaybackStopped code
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Labels: refactor

#1995 Remove commented log statements
  app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
Labels: refactor

#1994 Use SDK SortOrder enum in LibraryPreferences
  app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
Labels: sdk-migration, refactor

#1996 Use SDK in StartupActivity
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Labels: sdk-migration, refactor

#1997 Use MediaStream from SDK in MediaInfoCardView and InfoCardPresenter
  app/src/main/java/org/jellyfin/androidtv/ui/card/MediaInfoCardView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/InfoCardPresenter.java
Labels: sdk-migration, refactor

#1999 Remove USE_DOWNLOAD_API from picture viewer
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Labels: photos, refactor

#1998 Keep ordering from album view in picture viewer
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
Labels: bug, photos

#2000 Fix crash when trying to start a picture slideshow
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Labels: bug, photos, crash

#2002 Migrate most of KeyProcessor to SDK types
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: sdk-migration, refactor

#2013 Use SDK in HomeFragment
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
Labels: sdk-migration, refactor

#2014 Replace most utils with SDK
  app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/util/BlurHashUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/MediaUtils.java
  app/src/main/java/org/jellyfin/androidtv/util/Utils.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: sdk-migration, refactor

#2016 Migrate favorite and played toggles in KeyProcessor to SDK
  app/src/main/java/org/jellyfin/androidtv/data/repository/ItemMutationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Labels: sdk-migration, refactor

#2020 Fix crash when opening favorites and video queue
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
Labels: bug, crash

#2021 Remove unused video queue code
  app/src/main/java/org/jellyfin/androidtv/constant/LiveTvOption.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/res/drawable/ic_video_queue.xml
  app/src/main/res/drawable/tile_port_video_queue.xml
  app/src/main/res/values/attrs_tiles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/theme_emerald.xml
  app/src/main/res/values/theme_jellyfin.xml
Labels: refactor
