Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-12, with the labels that each got.

#2301 Remove mActivity from EnhancedBrowseFragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
Labels: refactor

#2297 Remember button focus on summary page
  app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt
Labels: enhancement

#2308 Fix LegacyImageCardView scaling on non-1080p devices
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Labels: bug, backportable

#2310 Rewrite session validation code to not use callbacks
  app/src/main/java/org/jellyfin/androidtv/auth/ui/ActivityAuthenticationExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/di/ActivityLifecycleCallbacksModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/KoinInitializer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/AbstractActivityLifecycleCallbacks.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
Labels: refactor, crash

#2320 Fix acra-core dependency using wrong name
  gradle/libs.versions.toml
Labels: dependencies

#2316 Fix crash when stopping playback with back button when refresh rate switching is enabled
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: crash

#2334 Split compose versions in catalog
  gradle/libs.versions.toml
Labels: dependencies, gradle

#2342 Remove direct path option from external player
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug, crash

#2345 Remember button focus on details screen
  app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt
Labels: enhancement

#2351 Fix race condition in ItemListFragment causing favorite music screen to crash
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
Labels: crash

#2354 Validate current user from UserRepository in validateAuthentication()
  app/src/main/java/org/jellyfin/androidtv/auth/ui/ActivityAuthenticationExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: crash

#2370 Update build files
  app/build.gradle.kts
  playback/core/build.gradle.kts
  playback/exoplayer/build.gradle.kts
  playback/jellyfin/build.gradle.kts
  playback/ui/build.gradle.kts
  preference/build.gradle.kts
  settings.gradle.kts
Labels: refactor

#2371 Fix scaling of album images in audio queue on now playing screen
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Labels: bug

#2373 Fix crash when opening menu for AlbumArtist
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Labels: bug, crash
