Repository jellyfin/jellyfin-androidtv, pull requests merged in 2022-11, with the labels that each got.

#2232 Rename xml layout starting with activity_ to fragment_
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/res/layout/fragment_audio_now_playing.xml
  app/src/main/res/layout/fragment_full_details.xml
  app/src/main/res/layout/fragment_item_list.xml
Labels: refactor

#2234 Update Jellyfin SDK to 1.4.0-beta.1
  gradle/libs.versions.toml
Labels: dependencies, gradle

#2240 Always reset navigation in StartupActivity
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Labels: bug

#2241 Fix app crash when playing trailers
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: bug, crash

#2245 Add Video Codec Tag
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: enhancement

#2239 Apply subtitle delay to external subs
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, playback, backportable

#2246 Avoid clearing all items on ItemRowAdapter load
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug

#2249 Fix bad version.ref in dependency catalog
  gradle/libs.versions.toml
Labels: bug

#2252 Add dismissible notification for beta releases
  app/src/main/java/org/jellyfin/androidtv/data/model/AppNotification.kt
  app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2254 Fix missing checkboxes in player audio, subtitle and zoom menu
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
Labels: bug

#2259 Delay home fragment refreshing
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
Labels: bug

#2265 Use ItemRowAdapterHelper.setItems for more row types
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug, crash

#2266 Fix EnhancedBrowseFragment duplicating items on resume
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
Labels: bug

#2271 Fix opening user view with no collection type
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Labels: crash

#2272 Fix NPE in ExternalPlayerActivity when getMediaSource() returns null
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
Labels: crash

#2284 Fix opening Live TV recordings
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Labels: crash

#2285 Fix opening Live TV series timers
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Labels: crash

#2286 Rewrite theme code to not use callbacks
  app/src/main/java/org/jellyfin/androidtv/di/ActivityLifecycleCallbacksModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/AppThemeCallbacks.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/ThemeManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
  app/src/main/java/org/jellyfin/androidtv/util/ActivityThemeExtensions.kt
Labels: refactor

#2295 Fix crash when opening Live TV series
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Labels: crash

#2299 Fix notification card not focusable on older Android versions
  app/src/main/res/layout/view_card_notification.xml
Labels: bug
