Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-03, with the labels that each got.

#2556 Add IncludeType param when sending number query
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
Labels: bug, backportable

#2563 Fix all string capitalization
  app/src/main/res/values/strings.xml
Labels: enhancement

#2560 Fix missing background in DreamContentLogo
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLogo.kt
Labels: bug

#2558 Add workaround for non reproducible baseline profiles in AGP
  app/baselineWorkaround.gradle
  app/build.gradle.kts
Labels: bug, backportable

#2564 Fix SearchFragment not restoring properly
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt
Labels: bug, backportable

#2567 Fix screensaver crash when loading an invalid backdrop image
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
Labels: bug, crash

#2587 Always check server id when retrieving user data from AccountManagerStore
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerUserRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/store/AccountManagerStore.kt
  app/src/main/java/org/jellyfin/androidtv/auth/store/AuthenticationPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemUserPicker.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
Labels: bug, backportable

#2585 Add blurHashPainter composable
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt
Labels: enhancement

#2589 Remove watched indicator from empty series
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
Labels: enhancement

#2591 Save accounts to account manager by address
  app/src/main/java/org/jellyfin/androidtv/auth/model/AccountManagerAccount.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/store/AccountManagerStore.kt
Labels: bug, authentication, backportable

#2593 Add media manager implementation using new playback module
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/core/src/main/kotlin/PlaybackManager.kt
  playback/core/src/main/kotlin/PlaybackRepository.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/backend/BackendService.kt
  playback/core/src/main/kotlin/backend/PlayerBackendEventListener.kt
  playback/core/src/main/kotlin/mediastream/MediaStream.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamService.kt
  playback/core/src/main/kotlin/queue/QueueService.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
Labels: enhancement, playback

#2594 Add androidx.media2 MediaSessionService implementation
  playback/core/src/main/AndroidManifest.xml
  playback/core/src/main/kotlin/mediasession/AndroidMediaService.kt
  playback/core/src/main/kotlin/queue/QueueService.kt
Labels: enhancement, playback

#2600 Update and specify full action versions
  .github/workflows/app-build.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
  .github/workflows/gradlew-validate.yaml
  .github/workflows/repo-stale.yaml
Labels: enhancement, ci, github-actions

#2621 Fix app closing when music queue ends
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug, backportable
