Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-08, with the labels that each got.

#2938 Fix wrong lifecycle state in NextUpFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
Labels: bug

#2939 Always use child fragment manager instead of activity fragment manager
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug, crash

#2940 Fix crash when reusing actions in MyDetailsOverviewRowPresenter
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
Labels: bug, crash

#2943 Fix UI corruption when resuming the FullDetailsFragment
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#2949 Improve BaseRowItem refreshing (fix crash after item deletion)
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
Labels: bug, crash

#2961 Fix ExoPlayerBackend not triggering onMediaStreamEnd correctly
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug

#2960 Fix crash when same item appears in queue multiple times
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
Labels: bug, crash

#2964 Add margin to media grid
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/res/layout/horizontal_grid_browse.xml
Labels: enhancement

#2984 Fix disabling subtitles not always working
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
Labels: bug

#2985 Always use user provided fast forward and rewind values
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: enhancement

#2996 Synochronise music timers
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#2995 Alignment changes to audio player
  app/src/main/res/layout/fragment_audio_now_playing.xml
Labels: enhancement

#3000 Remove Thread.sleep usages
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: refactor

#2979 Folder improvements
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/square_accent.xml
  app/src/main/res/layout/view_card_legacy_image.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/theme_jellyfin.xml
  app/src/main/res/values/theme_mutedpurple.xml
Labels: enhancement

#3012 Make aspect ratio setting use radio buttons
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
Labels: enhancement
