Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-10, with the labels that each got.

#3105 Fix playback stop reported twice
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Labels: bug

#3108 Enable support for Opus and FLAC in ExoPlayer
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: enhancement

#3090 Fix embedded subtitles not loading when subtitle filter on library
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug

#3113 Support remux/transcode fallback in new music player
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/backend/BackendService.kt
  playback/core/src/main/kotlin/backend/PlayerBackend.kt
  playback/core/src/main/kotlin/backend/PlayerBackendEventListener.kt
  playback/core/src/main/kotlin/mediastream/MediaStream.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamResolver.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamState.kt
  playback/core/src/main/kotlin/queue/PlayerQueueState.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
Labels: enhancement, playback

#3115 Fix display mode not changing back when closing player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug

#3133 Fix GridButtonPresenter focus on old Android platforms
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Labels: bug
