Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-09, with the labels that each got.

#3024 Fix sync issue in ItemRowAdapterHelper
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug

#3003 Fix grid getting focus when empty
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Labels: bug

#3035 Fix compose deprecations
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/time.kt
Labels: refactor

#3040 Fix ExternalPlayerActivity not using PreferenceStore.reset
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
Labels: bug

#3041 Remove old user preference migrations (before 0.15)
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
Labels: enhancement

#3046 Migrate ItemListView to SDK
  app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
  app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
Labels: sdk-migration, refactor

#3045 Fully migrate ItemLauncher to SDK
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncherHelper.kt
Labels: sdk-migration, refactor

#3020 Grab background images no larger than the screen
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
Labels: enhancement

#3005 Fix user image being too cropped in
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
  app/src/main/res/drawable/tile_user.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/values/attrs_tiles.xml
  app/src/main/res/values/theme_jellyfin.xml
  app/src/main/res/values/theme_mutedpurple.xml
Labels: bug

#3054 Restore session on MainActivity stop
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: bug, authentication

#3055 Migrate ExternalPlayerActivity (mostly) to SDK
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivityHelper.kt
Labels: enhancement, sdk-migration

#3058 Fix progress bar positioning in view_row_details
  app/src/main/res/layout/view_row_details.xml
Labels: bug

#3062 Add initial playback capability testing
  playback/core/src/main/kotlin/backend/PlayerBackend.kt
  playback/core/src/main/kotlin/mediastream/MediaStream.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamState.kt
  playback/core/src/main/kotlin/support/PlaySupportReport.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/exoplayer/src/main/kotlin/mapping/audio.kt
  playback/exoplayer/src/main/kotlin/mapping/container.kt
  playback/exoplayer/src/main/kotlin/support/AdaptiveSupport.kt
  playback/exoplayer/src/main/kotlin/support/DecoderSupport.kt
  playback/exoplayer/src/main/kotlin/support/ExoPlayerPlaySupportReport.kt
  playback/exoplayer/src/main/kotlin/support/FormatSupport.kt
  playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/tracks.kt
Labels: enhancement, playback

#3085 Use layer-list for app_banner drawable
  app/src/main/res/drawable-v24/app_banner_background.xml
  app/src/main/res/drawable-v24/app_banner_foreground.xml
  app/src/main/res/drawable/app_banner.xml
  app/src/main/res/drawable/app_banner_background.xml
  app/src/main/res/drawable/app_banner_foreground.xml
Labels: enhancement
