Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-07, with the labels that each got.

#2862 Fix horizontal grid position resetting on resume
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Labels: bug

#2864 Show UI mode notification on startup screen
  app/src/main/java/org/jellyfin/androidtv/data/model/AppNotification.kt
  app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
  app/src/main/res/layout/fragment_select_server.xml
  buildSrc/src/main/kotlin/Properties.kt
Labels: enhancement

#2880 Remove unused ProcessLifecycleInitializer
  app/src/main/java/org/jellyfin/androidtv/ProcessLifecycleInitializer.kt
Labels: refactor

#2879 Add missing view action to StartupActivity
  app/src/main/AndroidManifest.xml
Labels: bug, backportable

#2884 Fix application crash on startup
  app/src/main/AndroidManifest.xml
Labels: bug, crash

#2889 Replace Glide with Coil
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/androidtv/JellyfinGlideModule.kt
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  gradle/libs.versions.toml
Labels: enhancement

#2892 Add preference to disable device type detection notification
  app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/ContextExtensions.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2895 Fix video player background not black
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/res/layout/vlc_player_interface.xml
Labels: bug

#2893 Improve codec info
  CONTRIBUTORS.md
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: enhancement

#2920 Use data object in sealed interfaces
  app/src/main/java/org/jellyfin/androidtv/constant/CustomMessage.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationAction.kt
Labels: refactor

#2922 Add music progress to screensaver
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
Labels: enhancement

#2925 Replace flow.collect usages with onEach & launchIn
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/NotificationsHomeFragmentRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerAddViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerAddFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
  app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt
Labels: refactor

#2927 Add animation labels for Compose
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/ZoomBox.kt
Labels: enhancement

#2928 Simplify defaultRewindAmount and defaultFastForwardAmount options
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/PreferenceModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/PlaybackPreferenceBridge.kt
  app/src/main/java/org/jellyfin/androidtv/preference/PreferencesRepository.kt
  playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
  playback/core/src/main/kotlin/PlaybackManagerOptions.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
Labels: enhancement

#2929 Use rounded corner for item details image
  app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/res/drawable/shape_card.xml
  app/src/main/res/layout/fragment_audio_now_playing.xml
  app/src/main/res/layout/view_row_details.xml
Labels: enhancement

#2932 Fix crash when location type is null in CardPresenter
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
Labels: bug, crash
