Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-12, with the labels that each got.

#3206 Fix system screensaver starting during video playback
  app/src/main/java/org/jellyfin/androidtv/ui/ScreensaverViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: bug

#3207 Close video player on resume with invalid state
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug

#3205 Keep codec info displayed for HDR streams
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: enhancement

#3210 util: Don't use TZ offset for media Premiere Date
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Labels: bug

#3232 Fix crash when starting player where playback controller may be null
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
Labels: bug, crash

#3235 Remove unnecessary OptIn annotations
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
Labels: refactor

#3236 Fix RewriteMediaManager never used in production builds
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
Labels: bug

#3245 Fix focus issue when pressing back in Fire TV soft keyboard
  app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
Labels: bug

#3247 Fix playing audio from search queues entire row
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Labels: bug

#3246 Fix opening collections via search results showing empty screen
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java
Labels: bug

#3250 Fix crash and inconsistent ordering when using ShuffleOrderIndexProvider
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
  playback/core/src/main/kotlin/queue/PlayerQueueState.kt
  playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
Labels: bug, playback, crash

#3253 Disable SocketHandler when using RewriteMediaManager
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
Labels: bug, playback

#3265 Add <queries> element to Manifest for remote trailers
  app/src/main/AndroidManifest.xml
Labels: bug

#3266 Add more item types to search
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
