Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-06, with the labels that each got.

#2810 Add repeat mode to playback rewrite
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
  playback/core/src/main/kotlin/model/RepeatMode.kt
  playback/core/src/main/kotlin/queue/PlayerQueueState.kt
  playback/core/src/main/kotlin/queue/order/DefaultOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
Labels: enhancement, playback

#2815 Update unsupported server messages
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
  app/src/main/java/org/jellyfin/androidtv/util/RecommendedServerIssueExtensions.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2802 Enable playback rewrite by default for music
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2816 Fix Live TV progress reporting
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Labels: bug, live-tv, backportable

#2812 Fix InfoLayoutHelper not using first video stream, update details when selecting version
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
Labels: bug, enhancement

#2818 Fix ItemLauncher retrieving base item via from media manager when launching a photo
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Labels: bug

#2817 Add volume state to playback rewrite
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
  app/src/main/java/org/jellyfin/androidtv/di/AndroidModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
  playback/core/src/main/kotlin/PlaybackManagerOptions.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/PlayerVolumeState.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
Labels: enhancement, playback

#2825 Use fast forward & rewind durations from preferences
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/PreferenceModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/PlaybackPreferenceBridge.kt
  app/src/main/java/org/jellyfin/androidtv/preference/PreferencesRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
  playback/core/src/main/kotlin/PlaybackManagerOptions.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionService.kt
Labels: enhancement, playback

#2848 Fix crash when player controls are auto-hiding while closing the player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, crash

#2850 Add more logging to authentication code
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
Labels: enhancement, backportable
