Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-01, with the labels that each got.

#2381 Allow all supported audio codecs in ExoPlayer transcoding profile
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: enhancement, playback

#2380 Support fast forward and rewind in audio player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Labels: enhancement, playback

#2385 Fix IndexOutOfBoundsException in setExoPlayerTrack
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug, playback, crash

#2361 Show resumable episodes in smart screen for shows
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
Labels: enhancement

#2395 Fix BrowseGridFragment focus not restoring when going back
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Labels: bug, backportable

#2397 Remove experimental audio codecs from transcoding profile
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: bug, playback

#2420 Increase amount of logs added to crash reports
  app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt
Labels: enhancement, backportable

#2422 Ignore missing notification permission from Glide
  android-lint.xml
Labels: bug, dependencies

#2428 Add PlaySessionService to playback rewrite
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
Labels: enhancement, playback

#2442 Use HEADER_ACCEPT from SDK as Glide Accept header value
  app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
Labels: bug, backportable

#2441 Update playback module with SDK 1.4.1 changes
  playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
  playback/jellyfin/src/main/kotlin/queue/item/BaseItemDtoUserQueueEntry.kt
Labels: enhancement, playback

#2392 Add AV1 direct play support.
  app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Labels: enhancement, playback

#2443 Change opening menu to ACTION_UP instead of ACTION_DOWN
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
Labels: bug, backportable

#2445 Remove gradlew-update.yaml workflow
  .github/workflows/gradlew-update.yaml
Labels: refactor

#2415 Add media management preference
  app/src/main/java/org/jellyfin/androidtv/data/model/DataRefreshService.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2455 Add option to enable playback rewrite for audio
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, playback

#2458 Split MediaManager into MediaManager and VideoQueueManager
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoQueueManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: playback, refactor
