Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-02, with the labels that each got.

#2461 Remove selected photo item from MediaManager and do some more cleaning
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: playback, refactor

#2459 adds "shuffle with" button if "always ask" is selected as preferred player.
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: enhancement

#2468 Revert "Update dependency com.android.tools:desugar_jdk_libs to v2.0.1"
  gradle/libs.versions.toml
Labels: dependencies

#2469 Fix rare picture viewer crash when album is empty
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
Labels: bug, photos, backportable, crash

#2477 Update item delete confirm message string
  app/src/main/res/values/strings.xml
Labels: enhancement

#2472 Fix old items are shown when new filter is applied.
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
Labels: bug, backportable

#2491 Add androidx.compose.compiler to libraries section in version catalog
  gradle/libs.versions.toml
Labels: dependencies

#2517 Don't show "invalid credentials" message when authentication fails with an SDK exception
  app/src/main/java/org/jellyfin/androidtv/auth/model/LoginState.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
Labels: bug, backportable

#2519 Replace deprecated Bundle.get with Bundle.getParcelable
  app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditUserScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/BundleExtensions.kt
Labels: refactor

#2523 Remove playlist creation from NowPlaying screen
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/res/layout/fragment_audio_now_playing.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2534 Mark LibVLC as experimental
  app/src/main/res/values/strings.xml
Labels: enhancement

#2542 Only attach background service in activities
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
Labels: bug, backportable

#2543 Fix theme not applied before creating views
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Labels: bug, backportable

#2547 Accept KEYCODE_ENTER as alt to KEYCODE_CENTER
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
Labels: bug

#2553 Always use getQuantityString() for time units
  app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
  app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#2554 Fix crash when scaleType is null in AsyncImage
  app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt
Labels: bug

#2549 Update "Latest" media labels to be "Recently Added"
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
