Repository jellyfin/jellyfin-androidtv, pull requests merged in 2023-04, with the labels that each got.

#2629 Fix screenOrientation not set for PreferencesActivity
  app/src/main/AndroidManifest.xml
Labels: backportable, crash

#2634 Fix "null" on Live TV guide "load channels" button
  app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt
Labels: bug, live-tv

#2635 Add F-Droid badge to README
  README.md
Labels: enhancement

#2515 Improve Android TV home screen recommendations
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Labels: enhancement

#2641 Use ItemRowAdapterHelperKt.setItems for NextUpQuery in ItemRowAdapter
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
Labels: refactor

#2644 Add (experimental) reactive homepage
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2649 Fix playback rewrite audio queue in UI
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug, playback

#2652 Rewrite background service UI with compose
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundServiceFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: refactor

#2659 Fix BaseItemInfoRow not showing for persons
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
Labels: enhancement

#2572 Explicitly use JDK 17 through gradle toolchains
  build.gradle.kts
  buildSrc/build.gradle.kts
Labels: enhancement, dependencies, gradle

#2665 Enable nonFinalResIds
  app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationSortBy.kt
  app/src/main/java/org/jellyfin/androidtv/constant/GridDirection.kt
  app/src/main/java/org/jellyfin/androidtv/constant/HomeSectionType.kt
  app/src/main/java/org/jellyfin/androidtv/constant/ImageType.kt
  app/src/main/java/org/jellyfin/androidtv/constant/PosterSize.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/AppTheme.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/AudioBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/ClockBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/LiveTvChannelOrder.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/NextUpBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/RatingType.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/RefreshRateSwitchingBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/WatchedIndicatorBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/EnumDisplayOptions.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemEnum.kt
  gradle.properties
  preference/src/main/kotlin/PreferenceEnum.kt
  preference/src/main/kotlin/store/SharedPreferenceStore.kt
Labels: refactor

#2664 Enable nonTransitiveRClass
  app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapDialogFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorPickerDialogFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/DurationSeekBarPreference.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListDialogFragment.kt
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: refactor

#2668 Fix app crash when playback stop is requested without an active player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, backportable, crash

#2667 Add separate buttons for artists and album artists in music smart screen
  app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt
  app/src/main/java/org/jellyfin/androidtv/data/querying/AlbumArtistsQuery.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/res/drawable/tile_album_artists.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, release-highlight

#2670 Rewrite GridButton with Compose
  app/src/main/java/org/jellyfin/androidtv/ui/GridButton.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Labels: enhancement

#2692 Fix offsetStreamIndex when selecting last track
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug, playback, backportable

#2693 Fix support for switching embedded subtitle tracks in ExoPlayer
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, playback, backportable

#2691 Remove BaseProfile
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/profile/BaseProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
Labels: enhancement, refactor

#2694 Enable DVB subtitles in ExoPlayer
  app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: enhancement, playback, backportable

#2709 Fix ExpandableTextView cutting content
  app/src/main/res/layout/popup_expandable_text_view.xml
Labels: bug, backportable

#2710 Fix ExoPlayerProfile not always listing SubRip and SRT as external
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: bug, playback, backportable

#2712 Fix ExoPlayer extensions not used for music playback (backport)
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Labels: bug, playback

#2716 Allow changing the (a)ac3 bitstreaming option on all devices
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
Labels: enhancement, playback, backportable

#2723 Add support for retrieving resume items in BaseRowAdapter using the SDK
  app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug, sdk-migration, backportable
