Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-12, with the labels that each got.

#4269 Fix crash when viewing audio now playing while using Emerald theme
  app/src/main/res/drawable/audio_now_playing_album_background.xml
Labels: bug, crash

#4270 Fix crash when trying to report playback progress when there is no current stream
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, crash

#4275 Fix ItemRowAdapterHelper.refreshItem using wrong thread when invoking callback
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug, crash

#4276 Make playbackController reference optional in ReportingHelper
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Labels: bug

#4271 Always call notifyInteraction on navigation
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: bug, needs-testing

#4294 Update androidx.media3 to 1.5.0
  gradle/libs.versions.toml
Labels: dependencies

#4311 Fix external subtitles not added to external player
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
Labels: bug

#4322 Fix UI audio queue order when shuffling
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug

#4321 Prevent AudioNowPlayingFragment from showing without active queue
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#4324 Fix QueueService.getNextIndices returning one item too many when using REPEAT_ENTRY_ONCE
  playback/core/src/main/kotlin/queue/QueueService.kt
Labels: bug

#4329 Fix music play action not working after queue has ended
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug

#4339 Fix crash when starting progress report loop without active stream in video player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4338 Infer subtitle codec from delivery URL if unknown
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManagerHelper.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/audio.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/container.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/subtitle.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/video.kt
Labels: bug

#4253 Display media runtime in hour minute format
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#4341 Centralize requested item fields
  app/src/main/java/org/jellyfin/androidtv/data/repository/ItemRepository.kt
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: refactor

#4352 Enable audio focus for music playback
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: enhancement, playback

#4355 Replace Icons.Default.Done with ic_check in ConnectHelpAlertFragment
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt
  app/src/main/res/drawable/ic_check.xml
Labels: refactor

#4357 Fix Live TV remux fail-over not working
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, live-tv, backportable

#4362 Fix app crashing when playback reporting fails
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
Labels: bug, backportable, crash
