Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-11, with the labels that each got.

#4138 Don't close player with invalid state in onCreate
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, backportable

#4142 Consider artist images before album artist images
  app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
Labels: enhancement

#4143 Consider artist names before album artist names
  app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: enhancement

#4147 Add additional information to PlaybackStartInfo
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Labels: enhancement

#4148 Fix getSubtitleDeliveryMethod in StreamInfo always returning "Encoding"
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4150 Fix player crashing when playback failed
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, crash

#4154 Fix audio track selection when baking subtitles
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4164 Fix exo track id parsing for format change.
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug

#4169 Remove runBlocking usage in HomeRowsFragment
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
Labels: refactor

#4170 Catch errors when loading MediaSessionService artwork
  playback/media3/session/src/main/kotlin/MediaSessionService.kt
Labels: bug

#4168 Fix sorting TV shows by last played
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Labels: bug

#4167 Fix position on playback stop reporting when skipping to playback end
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4171 Catch errors when reporting playback state
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Labels: bug, crash

#4175 Use percentage seekbar for subtitle text size
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemSeekbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3794 Add option to customize seek time
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemSeekbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/ui/playback/overlay/CustomSeekProviderTests.kt
Labels: enhancement

#4189 Fix skipping to end of video reports wrong end time
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4190 Upgrade to Coil 3
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/coil/SubsetTransformation.kt
  gradle/libs.versions.toml
Labels: enhancement

#4195 Fix ImageProvider always throwing
  app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
Labels: bug, crash

#4196 Fix subtitle menu not always showing "None" as first item
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt
Labels: bug

#4197 Fix skipping to end of video reports wrong end time
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4201 Use relative index matching for subtitle selection
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
Labels: bug

#4202 Never load PGS externally
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: bug

#4203 Fix player UI not hiding automatically
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4206 Really never load PGS externally
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: bug

#4210 Refactor subtitle profiles to be more readable
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Labels: bug, refactor

#4211 Fix background of album in now playing screen when lyrics are displaying
  app/src/main/res/drawable/audio_now_playing_album_background.xml
  app/src/main/res/layout/fragment_audio_now_playing.xml
Labels: bug

#4217 Fix audio now playing screen always showing "1 of x" instead of the actual queue position
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug

#4221 Unset playing item once the playback queue ends
  playback/core/src/main/kotlin/queue/QueueService.kt
Labels: enhancement

#4228 Update dependency org.jellyfin.sdk:jellyfin-core to v1.6.3
  gradle/libs.versions.toml
Labels: dependencies, gradle

#4248 Specify fields in resumePlayback() API request
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
Labels: bug
