Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-06, with the labels that each got.

#3633 Start series from first unwatched in "play next up"
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
Labels: bug

#3638 Fix now playing fragment not using string resource for current queue title
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/res/values/strings.xml
Labels: bug

#3637 Remove some unused code related to ItemRowAdapter
  app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: refactor

#3639 Remove LibVLC
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/SettingsPopup.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VlcEventHandler.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SettingAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
  app/src/main/res/layout/settings_popup.xml
  app/src/main/res/layout/vlc_player_interface.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: refactor

#3640 Migrate "Recently added" to SDK
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: sdk-migration, refactor

#3644 Migrate Live TV rows to SDK
  app/src/main/java/org/jellyfin/androidtv/data/querying/GetSeriesTimersRequest.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: live-tv, sdk-migration, refactor

#3648 Reordering the trailer button
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: enhancement

#3653 Fix start letter & favorite playlist implementations for item row
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Labels: bug

#3656 Fix QuickConnect sticky login state
  app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
Labels: bug, authentication, backportable

#3658 Change 'Queue all subsequent episodes' setting to queue all episodes in a series
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3657 Send QueueEntry to playback backend
  playback/core/src/main/kotlin/PlaybackManager.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/backend/PlayerBackend.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamState.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
Labels: playback, refactor

#3660 Implement normalization gain for music tracks
  playback/core/src/main/kotlin/mediastream/normalizationGainElement.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerAudioPipeline.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/jellyfin/src/main/kotlin/queue/createBaseItemQueueEntry.kt
Labels: enhancement, playback

#3661 Fix play after pause in MediaManager implementation
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug

#3663 Simplify video player preference
  app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3665 Use SDK for FilterOptions
  app/src/main/java/org/jellyfin/androidtv/data/model/FilterOptions.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
Labels: sdk-migration, refactor

#3674 Add a blur to backdrop images
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
Labels: enhancement

#3684 Improve "continue listening" row
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/res/values/strings.xml
Labels: bug

#3687 Fix Live TV not playing video streams
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, live-tv

#3680 Add media logo to screensaver
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt
Labels: enhancement
