Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-04, with the labels that each got.

#3487 Add button to pick a random item to the smart screen
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#3488 Fix app_logo cutoff in some cases
  app/src/main/res/drawable-v24/app_logo.xml
  app/src/main/res/drawable/app_logo.xml
Labels: bug, backportable

#3477 Update SDK to 1.4.7 (10.8 with enum backports)
  gradle/libs.versions.toml
  playback/jellyfin/src/main/kotlin/mediastream/tracks.kt
Labels: enhancement

#3478 Update SDK to 1.4.7 (10.8 with enum backports)
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  playback/jellyfin/src/main/kotlin/mediastream/tracks.kt
Labels: enhancement

#3493 Remove non existent "SeriesTimers" collection type
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Labels: refactor

#3497 Split playback preferences into normal and advanced screens
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3262 Add home button when away from home view
  app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/shared/TitleView.kt
  app/src/main/res/layout/clock_user_bug.xml
  app/src/main/res/layout/fragment_audio_now_playing.xml
  app/src/main/res/layout/view_lb_browse_title.xml
  app/src/main/res/layout/view_lb_title.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/theme_jellyfin.xml
Labels: enhancement, release-highlight

#3507 Remove PlayAccess checks
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: refactor

#3513 Add preferences for screensaver age rating
  app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, release-highlight

#3523 Remove leakcanary
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies
