Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-05, with the labels that each got.

#3553 Force Quick Connect code to use LTR text direction
  app/src/main/res/layout/fragment_user_login_quick_connect.xml
Labels: bug, backportable

#3554 Refactor QueueEntry design
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/core/src/main/kotlin/element/ElementKey.kt
  playback/core/src/main/kotlin/element/ElementsContainer.kt
  playback/core/src/main/kotlin/element/delegates.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
  playback/core/src/main/kotlin/mediasession/MediaSessionService.kt
  playback/core/src/main/kotlin/mediasession/MetadataExtensions.kt
  playback/core/src/main/kotlin/mediastream/MediaStream.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamResolver.kt
  playback/core/src/main/kotlin/queue/EmptyQueue.kt
  playback/core/src/main/kotlin/queue/PagedQueue.kt
  playback/core/src/main/kotlin/queue/PlayerQueueState.kt
  playback/core/src/main/kotlin/queue/Queue.kt
  playback/core/src/main/kotlin/queue/QueueEntry.kt
  playback/core/src/main/kotlin/queue/QueueEntryMetadata.kt
  playback/core/src/main/kotlin/queue/SequenceQueue.kt
  playback/core/src/main/kotlin/queue/item/QueueEntry.kt
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueue.kt
  playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueue.kt
  playback/jellyfin/src/main/kotlin/queue/AudioTrackQueue.kt
  playback/jellyfin/src/main/kotlin/queue/EpisodeQueue.kt
  playback/jellyfin/src/main/kotlin/queue/baseItemElement.kt
  playback/jellyfin/src/main/kotlin/queue/createBaseItemQueueEntry.kt
  playback/jellyfin/src/main/kotlin/queue/item/BaseItemDtoUserQueueEntry.kt
Labels: enhancement, playback

#3555 Cache computed PlayableMediaStream in QueueEntry element
  playback/core/src/main/kotlin/mediastream/MediaStreamState.kt
  playback/core/src/main/kotlin/mediastream/QueueEntryMediaStream.kt
Labels: enhancement

#3558 Fix screensaver and media manager displaying video entries
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug, playback

#3559 Replace PlaybackForwardingActivity with PlaybackRewriteFragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt
Labels: playback, refactor

#3565 Add initial video codec testing
  playback/core/src/main/kotlin/mediastream/MediaStream.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/exoplayer/src/main/kotlin/mapping/container.kt
  playback/exoplayer/src/main/kotlin/mapping/video.kt
  playback/exoplayer/src/main/kotlin/support/ExoPlayerPlaySupportReport.kt
  playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/tracks.kt
Labels: enhancement, playback

#3566 Add media source selection
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/queue/mediaSourceIdElement.kt
Labels: enhancement, playback

#3472 Update to Kotlin SDK 1.5.0-beta.1 (Jellyfin 10.9)
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
  app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/LiveTvPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/LiveTvChannelOrder.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PlaybackSpeedAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/RecommendedServerIssueExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/ApiClientExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
  app/src/test/kotlin/ui/playback/VideoSpeedControllerTests.kt
  gradle/libs.versions.toml
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
  playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueue.kt
  playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueue.kt
  playback/jellyfin/src/main/kotlin/queue/EpisodeQueue.kt
Labels: enhancement

#3574 Fully migrate ItemListFragment to use SDK
  app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
Labels: sdk-migration, refactor

#3582 Fix "Add server" button not visible when there are too many servers
  app/src/main/res/layout/fragment_select_server.xml
Labels: bug, backportable

#3589 Remove unused code branch in BrowseViewFragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
Labels: refactor

#3603 Remove unused "Offline" item location
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/res/drawable/banner_edge_offline.png
Labels: enhancement

#3598 Refactor BaseRowItem to use inheritance
  app/src/main/java/org/jellyfin/androidtv/constant/ChangeTriggerType.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/AudioQueueBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/AudioQueueItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemPersonBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ChapterItemInfoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/GridButtonBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/SeriesTimerInfoDtoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragmentDelegate.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/res/values/strings.xml
Labels: bug, refactor

#3607 Fix ModelCompat crash for media type
  app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
Labels: bug, crash

#3605 Add app notification to notify about upcoming server requirement
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
  app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, backportable

#3615 Fix app crash in EditServerScreen
  app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt
Labels: bug, crash

#3625 Fix resumable episodes showing up twice in "Play next" integration
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Labels: bug

#3624 Migrate "next up" row to SDK
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: sdk-migration, refactor

#3627 Fix JSON decode crash in PictureViewerFragment
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Labels: bug, crash

#3629 Fix unchecked warning in FullDetailsFragment
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: bug
