Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-08, with the labels that each got.

#3824 Support float preferences
  app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt
  preference/src/main/kotlin/Preference.kt
  preference/src/main/kotlin/store/PreferenceStore.kt
  preference/src/main/kotlin/store/SharedPreferenceStore.kt
  preference/src/test/kotlin/PreferenceStoreTests.kt
Labels: enhancement

#3826 Strip HTML from descriptions in leanback integration
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt
Labels: bug, backportable

#3828 Fix race condition in PictureViewerViewModel
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
Labels: bug, backportable, crash

#3829 Fix AudioNowPlayingFragment showing wrong item in extremely rare cases
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug, backportable

#3820 Add Google Chromecast HD limitation
  CONTRIBUTORS.md
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
Labels: enhancement, backportable

#3833 Rewrite media queuing
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  playback/core/src/main/kotlin/PlaybackManager.kt
  playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
  playback/core/src/main/kotlin/PlayerState.kt
  playback/core/src/main/kotlin/mediastream/MediaStreamService.kt
  playback/core/src/main/kotlin/queue/EmptyQueue.kt
  playback/core/src/main/kotlin/queue/Queue.kt
  playback/core/src/main/kotlin/queue/QueueService.kt
  playback/core/src/main/kotlin/queue/order/DefaultOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/supplier/PagedQueueSupplier.kt
  playback/core/src/main/kotlin/queue/supplier/QueueSupplier.kt
  playback/core/src/main/kotlin/queue/supplier/SequenceQueueSupplier.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
  playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueueSupplier.kt
  playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueueSupplier.kt
  playback/jellyfin/src/main/kotlin/queue/AudioTrackQueueSupplier.kt
  playback/jellyfin/src/main/kotlin/queue/EpisodeQueueSupplier.kt
  playback/media3/session/src/main/kotlin/MediaSessionPlayer.kt
  playback/media3/session/src/main/kotlin/MediaSessionService.kt
Labels: enhancement, playback, refactor

#3837 Fix NullPointerException in CustomPlaybackOverlayFragment.onResume
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, backportable, crash

#3839 Fix RewriteMediaManager emitting onQueueStatusChanged with a queue when there is no audio items available
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug

#3840 Fix NullPointerException in LeanbackOverlayFragment.onPause
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
Labels: bug, backportable, crash

#3844 Use direct stream as default audio behavior
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
Labels: enhancement, backportable

#3863 Graduate reactive homepage to stable
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
Labels: enhancement, release-highlight, backportable

#3871 Fix crash when starting next episode
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
Labels: bug, backportable, crash

#3872 Fix intros showing next up screen
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: bug, backportable

#3862 Improve InfoRow colors/font readability
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowColors.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt
Labels: enhancement, release-highlight, backportable

#3873 Reset display mode when exiting video player
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, backportable

#3874 Fix InfoRow not using requested media source
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.kt
Labels: bug, backportable

#3882 Fix crash when item doesn't have a default audio/subtitle stream
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
Labels: bug, backportable, crash

#3892 Enable constant bitrate seeking
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: enhancement, backportable

#3893 Use device profile builder in jellyfinPlugin
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
Labels: refactor

#3902 Fix channels interpreted as Live TV channels
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
Labels: bug, backportable

#3908 Fix toggling favorites in ItemListFragment
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
Labels: bug, backportable

#3916 Disable direct play when encountering playback error twice
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: enhancement, backportable

#3928 Set seek parameter for D-Pad to 10 seconds
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.kt
  app/src/test/kotlin/ui/playback/overlay/CustomSeekProviderTests.kt
Labels: enhancement

#3933 Fix capitalization in video profiles causing invalid transcodes
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Labels: bug, backportable
