Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-07, with the labels that each got.

#3708 Fix skip to previous/next playback actions
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#3709 Fix header position in BrowseFolderFragment
  app/src/main/res/layout/view_lb_browse_title.xml
Labels: bug

#3712 Fix PlaySessionService no longer reporting to server
  playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
Labels: bug

#3713 Fix crash when re-opening app during music playback
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug, crash

#3720 Fix isPlayingAudio behavior
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Labels: bug, playback, backportable

#3723 Fix crash when refreshing current item
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug, crash

#3724 Shrink BaseItemInfoRowRuntime size
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
Labels: enhancement

#3729 Rewrite details row with constraint layout
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
  app/src/main/res/drawable/expanded_text.xml
  app/src/main/res/layout/view_row_details.xml
Labels: enhancement

#3731 Fix crash when item has no media sources
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, crash

#3735 Fix authorization for transcoding
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt
  playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
Labels: bug

#3737 Add direct play support for WAV audio
  playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
Labels: enhancement, playback

#3746 Fix "Next episode(s)" row not showing
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
Labels: bug

#3751 Fix race condition in player backdrop
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: bug

#3752 Fix AudioNowPlayingFragment showing "From null" when there is no album name
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#3755 Improve intro loading in SdkPlaybackHelper
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: refactor

#3760 Update editor config
  .editorconfig
Labels: enhancement

#3761 Fix timezone issues in Live TV guide
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
Labels: bug, live-tv

#3762 Remove unused compat streaminfo code
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
Labels: refactor

#3767 Replace all left-over Date usages with java.time
  app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuide.kt
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/util/ContextExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/util/DateTimeExtensions.kt
  app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: refactor

#3774 Fix FullDetailsFragment duplicating buttons on resume
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt
Labels: bug

#3781 Split "playback/exoplayer" Gradle module into two
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  playback/exoplayer/src/main/kotlin/ExoPlayerPlugin.kt
  playback/media3/exoplayer/build.gradle.kts
  playback/media3/exoplayer/src/main/AndroidManifest.xml
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerAudioPipeline.kt
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerOptions.kt
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerPlugin.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/audio.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/container.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/video.kt
  playback/media3/exoplayer/src/main/kotlin/support/AdaptiveSupport.kt
  playback/media3/exoplayer/src/main/kotlin/support/DecoderSupport.kt
  playback/media3/exoplayer/src/main/kotlin/support/ExoPlayerPlaySupportReport.kt
  playback/media3/exoplayer/src/main/kotlin/support/FormatSupport.kt
  playback/media3/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
  playback/media3/session/build.gradle.kts
  playback/media3/session/src/main/AndroidManifest.xml
  playback/media3/session/src/main/kotlin/AndroidMediaService.kt
  playback/media3/session/src/main/kotlin/Media3SessionPlugin.kt
  playback/media3/session/src/main/kotlin/MediaSessionOptions.kt
  playback/media3/session/src/main/kotlin/MediaSessionPlayer.kt
  playback/media3/session/src/main/kotlin/MediaSessionService.kt
  playback/media3/session/src/main/kotlin/MetadataExtensions.kt
  settings.gradle.kts
Labels: refactor

#3786 Disable tunneling
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug

#3785 Remove unused dtsEnabled preference
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3788 Add PCM_S16LE, PCM_S20LE and PCM_S24LE to supported audio codecs
  app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: enhancement, playback

#3790 Fix NPE when opening Live TV guide for the first time
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
Labels: bug

#3802 Fix "other" items in ByLetterFragment
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
Labels: bug

#3803 Fix nullability in copyWith[Series]TimerId functions
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCellHelper.kt
Labels: bug, live-tv, crash

#3807 Update targetSdk to 34
  app/build.gradle.kts
  gradle/libs.versions.toml
  playback/core/build.gradle.kts
  playback/jellyfin/build.gradle.kts
  playback/media3/exoplayer/build.gradle.kts
  playback/media3/session/build.gradle.kts
  preference/build.gradle.kts
Labels: enhancement

#3808 Fix record buttons in LiveProgramDetailPopup swapped
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
Labels: bug, live-tv

#3809 Fix Live TV program popup not populating when opening early
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, live-tv
