Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-01, with the labels that each got.

#3286 Disable crossfading for CardLegacyImageView to fix scaling issue
  app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
  app/src/main/res/layout/view_card_legacy_image.xml
Labels: bug

#3291 Defer home initialization until user info is available
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
Labels: bug, crash

#3296 Disable tunneling
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug, playback

#3292 Show specials for seasons
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
Labels: enhancement

#3301 Show specials for series
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: enhancement

#3288 Support setting audio and subtitle streams via remote control
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
Labels: enhancement

#3321 Remove legacy media manager implementation
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/res/values/strings.xml
Labels: refactor

#3322 Simplify MediaManager interface
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Labels: refactor

#3332 Use LTR for default subtitle direction
  app/src/main/res/layout/vlc_player_interface.xml
Labels: bug, backportable

#3333 Remove baseline workaround
  app/baselineWorkaround.gradle
  app/build.gradle.kts
Labels: refactor
