Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-02, with the labels that each got.

#3348 android tv hls playback direct play fix
  app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
  app/src/test/kotlin/util/DeviceUtilsTests.kt
Labels: bug

#3350 Use data object when applicable
  app/src/main/java/org/jellyfin/androidtv/auth/model/LoginState.kt
  app/src/main/java/org/jellyfin/androidtv/auth/model/QuickConnectState.kt
  app/src/main/java/org/jellyfin/androidtv/data/querying/ViewQuery.kt
  playback/core/src/main/kotlin/queue/EmptyQueue.kt
Labels: refactor

#3360 Fix downmixing AAC to stereo audio in exoplayer
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: bug

#3366 Only show PG-13 content in screensaver
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
Labels: enhancement, backportable

#3369 Specify BUILD_TOOLS_VERSION for r0adkll/sign-android-release step in publish workflow
  .github/workflows/app-publish.yaml
Labels: bug, ci, github-actions

#3371 Fix crash when updating clock in FullDetailsFragment while item information is unavailable
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Labels: bug, backportable

#3372 Remove "auto" max bit rate and add additional values
  app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/androidtv/constant/QualityProfiles.kt
  app/src/main/java/org/jellyfin/androidtv/di/UtilsModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/AutoBitrate.kt
  app/src/main/java/org/jellyfin/androidtv/util/Utils.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3376 Replace CoroutineUtils.runBlocking with new CoroutineUtils.runOnLifecycle
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Labels: bug, backportable, crash

#3386 Fix DPAD_CENTER on screensaver not handled
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyEventExtensions.kt
Labels: bug, backportable

#3379 Rewrite BaseItemInfoRow with Compose
  app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
  app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowColors.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/strings.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3391 Fix crash in SocketHandler.onPlayMessage when user id is not set
  app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
Labels: bug, backportable, crash

#3399 Fix crash when checking whether a person is a folder or not
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Labels: bug, backportable, crash

#3408 Replace deprecated rememberKoinInject with koinInject
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
Labels: refactor

#3407 Remove "automatically choose" option from video player preference
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#3409 Add "clear image cache" button to developer preferences
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#3410 Add fallthrough to media3 MimeTypes in codec->mime type mapping
  playback/exoplayer/src/main/kotlin/mapping/audio.kt
  playback/exoplayer/src/main/kotlin/mapping/container.kt
  playback/exoplayer/src/main/kotlin/mapping/video.kt
Labels: enhancement, playback
