Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-10, with the labels that each got.

#4025 Add preference to delay start of video
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4058 Fix Detekt max line length not matching Editorconfig
  detekt.yaml
Labels: bug

#4057 Fix video player not closing when fragment is stopped
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, backportable

#4064 Don't skip media segments shorter than 1 second
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/MediaSegmentExtensions.kt
Labels: enhancement

#4068 Add "ask to skip" media segment action
  app/src/main/java/org/jellyfin/androidtv/ui/composable/overscan.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/SkipOverlayView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt
  app/src/main/res/layout/vlc_player_interface.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#4020 Add preference for default zoom mode
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/ZoomMode.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4071 Remove DeviceUtils
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
Labels: refactor

#4072 Fix skipping to next episode
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
Labels: bug

#4080 Use Java 21 in jvm toolchain
  .github/workflows/app-build.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  gradle/libs.versions.toml
Labels: gradle, refactor

#4081 Use parcelable array list in DestinationFragmentView saved state
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
Labels: bug, backportable

#4082 Update package for Koin viewModel import
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Labels: refactor

#4041 Change upcomingMinimumServerVersion to 10.10.0 to warn about upcoming 10.10 requirement
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
Labels: enhancement, backportable

#4090 (0.17.z) Fix playing subsequent episode not working
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug

#4098 Fix PlaybackController not always disabling default track
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4107 Implement lyrics
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/LyricsBox.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/modifier/fadingEdges.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/modifier/overscan.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt
  app/src/main/res/layout/fragment_audio_now_playing.xml
  playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
  playback/jellyfin/src/main/kotlin/lyrics.kt
Labels: enhancement, release-highlight

#4111 Use "Ask to skip" by default for intros and outros
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt
Labels: enhancement

#4112 Automatically disable subtitles when baking fails
  app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug

#4115 Rewrite reporting helper with SDK
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Labels: sdk-migration, refactor

#4118 Sync custom controls with built-in controls in leanback overlay
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
  app/src/main/res/layout/vlc_player_interface.xml
Labels: bug

#4119 Hide video player controls by default
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
  app/src/main/res/layout/vlc_player_interface.xml
Labels: enhancement

#4122 Fix video restarting immediately when baking subtitles
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
Labels: bug

#4136 Add missing audioCodec to music transcode
  playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
Labels: bug, backportable
