Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-03, with the labels that each got.

#3425 Remove non-profile usages of DeviceUtils
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/AudioBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
  app/src/test/kotlin/util/DeviceUtilsTests.kt
Labels: enhancement

#3439 Update CI to new repository secrets and layout
  .github/workflows/app-publish.yaml
Labels: ci, github-actions, backportable

#3440 Update CI to new repository secrets and layout
  .github/workflows/app-publish.yaml
Labels: ci, github-actions, backportable

#3411 Use fully transparent background during video playback
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/res/layout/preference_button_remap.xml
  app/src/main/res/layout/preference_color_list.xml
  app/src/main/res/layout/preference_rich_list.xml
  app/src/main/res/layout/vlc_player_interface.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/theme_emerald.xml
  app/src/main/res/values/theme_jellyfin.xml
Labels: bug, backportable

#3438 Recreate icon/banner resources
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/res/drawable-v24/app_banner_background.xml
  app/src/main/res/drawable-v24/app_banner_foreground.xml
  app/src/main/res/drawable-v24/app_icon_background.xml
  app/src/main/res/drawable-v24/app_icon_background_round.xml
  app/src/main/res/drawable-v24/app_icon_foreground.xml
  app/src/main/res/drawable-v26/app_icon_foreground_padded.xml
  app/src/main/res/drawable/app_banner.xml
  app/src/main/res/drawable/app_banner_background.xml
  app/src/main/res/drawable/app_banner_foreground.xml
  app/src/main/res/drawable/app_icon.xml
  app/src/main/res/drawable/app_icon_background.xml
  app/src/main/res/drawable/app_icon_background_round.xml
  app/src/main/res/drawable/app_icon_foreground.xml
  app/src/main/res/drawable/app_icon_foreground_monochrome.xml
  app/src/main/res/drawable/app_icon_round.xml
  app/src/main/res/mipmap-anydpi-v26/app_icon.xml
  app/src/main/res/mipmap-hdpi/app_banner.png
  app/src/main/res/mipmap-hdpi/app_icon.png
  app/src/main/res/mipmap-mdpi/app_banner.png
  app/src/main/res/mipmap-mdpi/app_icon.png
  app/src/main/res/mipmap-xhdpi/app_banner.png
  app/src/main/res/mipmap-xhdpi/app_icon.png
  app/src/main/res/mipmap-xxhdpi/app_banner.png
  app/src/main/res/mipmap-xxhdpi/app_icon.png
  app/src/main/res/mipmap-xxxhdpi/app_banner.png
  app/src/main/res/mipmap-xxxhdpi/app_icon.png
  app/src/main/res/xml/authenticator.xml
  app/src/main/res/xml/searchable.xml
  fastlane/metadata/android/en-US/images/featureGraphic.png
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/tvBanner.png
Labels: enhancement, backportable

#3442 Fix background color for preference list views
  app/src/main/res/layout/preference_button_remap.xml
  app/src/main/res/layout/preference_color_list.xml
  app/src/main/res/layout/preference_rich_list.xml
Labels: bug, backportable

#3447 Fix search action ignoring received query
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
  app/src/main/res/layout/fragment_search_text.xml
Labels: bug, backportable

#3448 Improve info row colors
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowColors.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt
Labels: enhancement

#3417 Enable Vorbis audio in video direct play
  app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Labels: enhancement

#3475 Check if fragment is null in PlaybackController.play
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, backportable
