Repository jellyfin/jellyfin-androidtv, pull requests merged in 2024-09, with the labels that each got.

#3951 Update DeviceUtils with Xiaomi TV Stick
  app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
Labels: enhancement, backportable

#3959 Fix current fragment not removed on back press
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
Labels: bug, backportable

#3953 Add resolution codec check
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Labels: enhancement

#3997 Fix back press callback in CustomPlaybackOverlayFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: bug, backportable, crash

#4012 Increase amount of home sections from 7 to 10
  app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/HomePreferencesScreen.kt
Labels: enhancement

#4011 Implement My media (small) home section
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentViewsRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/UserViewCardPresenter.kt
Labels: enhancement

#4015 Fix aspect ratio specials
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
Labels: bug, backportable

#4023 Change upcomingMinimumServerVersion to 10.9.11 to encourage updating
  app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
Labels: enhancement, backportable

#4028 Fix incorrectly navigating on resume
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: bug, backportable

#4030 Fix queue not advancing
  playback/core/src/main/kotlin/queue/QueueService.kt
Labels: bug

#4031 Add flow support for elements
  playback/core/src/main/kotlin/element/ElementsContainer.kt
  playback/core/src/main/kotlin/element/delegates.kt
  playback/core/src/main/kotlin/mediastream/QueueEntryMediaStream.kt
  playback/core/src/main/kotlin/mediastream/normalizationGainElement.kt
  playback/core/src/main/kotlin/queue/QueueEntryMetadata.kt
  playback/jellyfin/src/main/kotlin/queue/baseItemElement.kt
  playback/jellyfin/src/main/kotlin/queue/mediaSourceIdElement.kt
Labels: enhancement

#4033 Rewrite NowPlayingView in compose
  app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
  app/src/main/res/layout/view_now_playing.xml
Labels: enhancement
