Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-08, with the labels that each got.

#4821 Finer subtitle size control
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
Labels: enhancement

#4837 Remove logo from screensaver
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
Labels: enhancement

#4835 Target Android 16 (API 36)
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: enhancement

#4861 Add display information to playback report
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
Labels: enhancement

#4862 Add display HDR capabilities to device profile
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
Labels: enhancement, needs-testing

#4865 Add new video player UI
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerHeader.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerOverlayLayout.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerSubtitles.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerSurface.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/visibilityTimer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerControls.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerHeader.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerOverlay.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerScreen.kt
Labels: enhancement

#4825 Add preference for subtitle position offset
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4882 Fix focus always forced to first queue item in AudioNowPlayingFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Labels: bug

#4883 Fix navigation issues in AudioNowPlayingFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/res/layout/fragment_audio_now_playing.xml
Labels: bug

#4885 Trim whitespace from search query
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchViewModel.kt
Labels: enhancement

#4889 Rewrite picture viewer in compose
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/FadeViewSwitcherLayout.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ScreensaverLock.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerOverlayLayout.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerContent.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerControls.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerHeader.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerOverlay.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/photo/PhotoPlayerViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  app/src/main/res/layout/fragment_picture_viewer.xml
Labels: enhancement, photos

#4891 Use transparent buttons in player controls
  app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerOverlayLayout.kt
Labels: enhancement
