Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-05, with the labels that each got.

#4635 Add intermediate model for image information
  app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
  app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpItemData.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/JellyfinImage.kt
Labels: enhancement

#4638 Use new intermediate model in most places
  app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
  app/src/main/java/org/jellyfin/androidtv/ui/presentation/UserViewCardPresenter.kt
  app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/ModelExtensions.kt
Labels: enhancement

#4640 Fix crash on startup
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
Labels: bug, backportable, crash

#4652 Always create boxset queues with default sorting instead of using sort names of individual items
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: blocked

#4650 Improve status bar hiding behavior
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Labels: enhancement

#4619 Change screensaver to cycle through random selection and avoid repeats
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
Labels: enhancement

#4668 Fix compose focus deprecations
  app/src/main/java/org/jellyfin/androidtv/ui/base/modifier/childFocusRestorer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
Labels: refactor

#4680 Update jellyfin-androidx-media to 1.6.1+1
  gradle/libs.versions.toml
Labels: dependencies, gradle

#4688 Fix screensaver request loop when there are no items to showcase
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
Labels: bug

#4686 Allow Exoplayer to invalidate the track selection on capabilities change
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug, backportable
