Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-04, with the labels that each got.

#4558 Add season and episode numbers for Live TV programs
  app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Labels: enhancement

#4560 Use OkHttp for networking in media3
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  gradle/libs.versions.toml
  playback/media3/exoplayer/build.gradle.kts
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerOptions.kt
Labels: enhancement

#4562 Rewrite toolbar in compose
  app/src/main/java/org/jellyfin/androidtv/ui/base/button/Button.kt
  app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonDefaults.kt
  app/src/main/java/org/jellyfin/androidtv/ui/base/button/IconButton.kt
  app/src/main/java/org/jellyfin/androidtv/ui/base/modifier/autoFocus.kt
  app/src/main/java/org/jellyfin/androidtv/ui/base/modifier/childFocusRestorer.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/HomeToolbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/StartupToolbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/Toolbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/StartupToolbarFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_toolbar_startup.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/theme_emerald.xml
  app/src/main/res/values/theme_jellyfin.xml
  gradle/libs.versions.toml
Labels: enhancement, ux

#4582 Fix experimental audio night mode feature crashing the app
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Labels: bug, backportable, crash

#4584 Do not set audio session to pipeline on create
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: bug

#4592 Fix "favorites" playlist not showing when the user has no playlists
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Labels: bug, backportable

#4591 Move activity opening out of navigation code
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/ActivityDestinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destination.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: enhancement

#4593 Add hearing impaired indicator for subtitles (SDH)
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4298 Fix watch next row ordering, Change watch next row meta data
  app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Labels: bug

#4605 Drop leanback implementation of search
  app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: enhancement

#4503 Add Rewind & FastForward buttons to AudioNowPlayingFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/res/drawable/ic_fast_forward.xml
  app/src/main/res/drawable/ic_rewind.xml
  app/src/main/res/layout/fragment_audio_now_playing.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#4615 Replace leanback animations with our own definitions in CustomPlaybackOverlayFragment
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/res/anim/slide_bottom_in.xml
  app/src/main/res/anim/slide_top_in.xml
Labels: enhancement
