Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-06, with the labels that each got.

#4697 Fix URL generation for user profile pictures
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/JellyfinImage.kt
Labels: bug

#4679 Change/Fix Resume Button Behaviour on Series
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4698 New search design
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/androidtv/ui/base/colorScheme.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchTextInput.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchVoiceInput.kt
  app/src/main/java/org/jellyfin/androidtv/util/speech/SpeechRecognizerState.kt
  app/src/main/java/org/jellyfin/androidtv/util/speech/SpeechRecognizerStatus.kt
  app/src/main/java/org/jellyfin/androidtv/util/speech/speechRecognizer.kt
  app/src/main/res/drawable/ic_microphone.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement, release-highlight

#4722 Clear skip overlay before applying media segments
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
Labels: bug, backportable

#4729 Add option to disable PGS direct play
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4509 Add still watching feature
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
  app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
  app/src/main/java/org/jellyfin/androidtv/preference/constant/StillWatchingBehavior.kt
  app/src/main/java/org/jellyfin/androidtv/ui/InteractionTrackerViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/ScreensaverViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingItemData.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingPresetConfigs.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingState.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingStates.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/stillwatching/StillWatchingViewModel.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/screensaver/InAppScreensaver.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, release-highlight

#4737 Don't attempt to load logo in screensaver when there is none
  app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
Labels: bug

#4745 KGP: replace kotlinOptions with compilerOptions
  build.gradle.kts
Labels: gradle, refactor
