Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-01, with the labels that each got.

#4365 Dismiss playback actions popups on fragment detach
  CONTRIBUTORS.md
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PlaybackSpeedAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
Labels: bug, backportable, crash

#4377 Prevent seeking from crashing app if video info is not initialized yet
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, backportable, crash

#4369 update issue forms
  .github/ISSUE_TEMPLATE/bug-report-playback.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: enhancement

#4347 Run LeanbackHelper onStop() to refresh home screen
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Labels: enhancement

#4385 Fix crash when favoriting Live TV program while loading additional channels in the guide
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
Labels: bug, backportable, crash

#4397 Trust user added CA certificates
  android-lint.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/network_security_config.xml
Labels: enhancement, backportable

#4411 Fix codec keys in new playback module
  CONTRIBUTORS.md
  playback/media3/exoplayer/src/main/kotlin/mapping/audio.kt
  playback/media3/exoplayer/src/main/kotlin/mapping/video.kt
Labels: enhancement

#4428 Update reported client name
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Labels: enhancement
