Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-07, with the labels that each got.

#4765 Fix retrieveAndPlay incorrectly using ticks instead of milliseconds as start position
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: bug, backportable

#4761 Fix LiveTV Guide Issue #2144
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
Labels: bug

#4768 Fix retrieveAndPlay incorrectly using ticks instead of milliseconds as start position
  app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Labels: bug

#4713 Keep same audio language while binge watching a series
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoQueueManager.kt
Labels: enhancement

#4780 Support removing items from playback queue
  app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt
  app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/AudioQueueBaseRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
  app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioQueueBaseRowAdapter.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
  app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
  playback/core/src/main/kotlin/queue/Queue.kt
  playback/core/src/main/kotlin/queue/QueueService.kt
  playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt
  playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
Labels: enhancement, playback

#4785 Query based on seriesId in FullDetailsFragmentHelper.getNextUpEpisode
  app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
Labels: bug, crash

#4786 Fix AsyncImageView.load showing incorrect images on rapid changes
  app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
Labels: bug, backportable

#4777 Start Live TV player when activating channel header
  app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
Labels: enhancement

#4798 Catch API issues in StartupActivity when opening a library
  app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Labels: bug

#4797 Prefer imageVector painting for icon drawables
  app/src/main/java/org/jellyfin/androidtv/ui/ServerButtonView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt
  app/src/main/java/org/jellyfin/androidtv/ui/card/UserCardView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/SkipOverlayView.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchTextInput.kt
  app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchVoiceInput.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/MainToolbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/StartupToolbar.kt
  app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt
Labels: refactor

#4802 Differentiate client name for debug version in API authorization
  app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Labels: enhancement

#4814 Run Detekt from root module only
  build.gradle.kts
Labels: bug, ci, gradle, backportable

#4685 Use overlay rendering for experimental SSA support
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
  gradle/libs.versions.toml
  playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Labels: enhancement
