Repository jellyfin/jellyfin-androidtv, pull requests merged in 2025-02, with the labels that each got.

#4438 Decouple external video playback from internal playback code
  app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivityHelper.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoQueueManager.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExternalPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Labels: enhancement, sdk-migration

#4455 Rewrite PlaybackManager with SDK
  app/src/main/java/org/jellyfin/androidtv/data/compat/AudioOptions.kt
  app/src/main/java/org/jellyfin/androidtv/data/compat/PlaybackException.kt
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamBuilder.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
  app/src/main/java/org/jellyfin/androidtv/data/compat/SubtitleStreamInfo.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt
  app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
Labels: enhancement, playback, sdk-migration

#4423 Subtitles background opacity
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/ColorUtils.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4481 Use media3 MimeTypes in deviceProfile
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
Labels: bug

#4480 Use color type in OptionsColorList
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorListPreference.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorPickerDialogFragment.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsColorList.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/ColorUtils.kt
Labels: refactor

#4483 Fix progress bar calculation
  app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Labels: bug, live-tv, backportable

#4482 Add button to report device profile to server for troubleshooting
  app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
  app/src/main/java/org/jellyfin/androidtv/util/MarkdownBuilder.kt
  app/src/main/java/org/jellyfin/androidtv/util/Utils.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
  app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#4492 Fix filtering not working in collections view
  app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
Labels: bug, backportable

#4491 Fix crash when switching subtitle track to non existent index
  app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
Labels: bug, backportable, crash
